language: cpp

compiler:
  - clang
  - gcc

sudo: required

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libjsoncpp-dev meson ninja-build

script:
  - mkdir build
  - meson build
  - cd build
  - ninja
