language: cpp

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  - SH="docker exec -t ubuntu-bionic bash -c"

before_install:
  - docker run -d --name ubuntu-bionic -v $(pwd):/travis -w /travis ubuntu:bionic tail -f /dev/null

install:
  - $SH "apt update"
  - $SH "apt install -y pkg-config libsystemd-dev libjsoncpp-dev googletest meson clang-format"

notifications:
  irc:
    channels:
      - "chat.freenode.net#oomd"
    on_success: change
    on_failure: always

script:
  - $SH ./build-from-github.sh
  - $SH './clang-format.sh && if [ $(git diff HEAD | wc -l) == "0" ]; then exit 0; else exit 1; fi'
